.
gurbuzertunga/bubble_sort pull request #1
Opened 2020-08-14 12:32 UTC by mahmoud717

sadasd

2020-08-14 21:50 UTC, ikraamg requested changes
Hi @mahmoud717 and @gurbuzertunga 

### **Status: Almost there! Minor changes required** :recycle: 

Great work! Your bubble sort algorithm has the correct logic and you have a good readme file.

A couple of things need to be fixed before we can have this merged: 

- [ ] Please ensure you write descriptive commit messages, this is very important for code history both as an individual and within a team.

- [ ] Please be a bit more descriptive in your PR descriptions as this gives context to the code reviewers. Very important when working within a team. 

- [ ] This might feel pedantic but the methods don't actually return anything. They print the array to the console but if you called these functions as part of a larger program, the functions would just return nil rather than the sorted array.
- [ ] Please remove the 'print' and create a return statement at the end of your function instead. To test if this works, you can call the method `puts bub_sort(arr)` and it should print to the console without having a print statement inside your method. 
- As a general note, remember to not have any 'debugging' code in your final PR such as printing to the console. 

If you have any questions, don't hesitate to contact me through slack: **_@ikraam_**

_**I wish you all the best!**_  :desktop_computer: 

_Project reviewed by Ikraam Ghoor (TSE)_

2020-08-14 21:50 UTC, ikraamg commented on bubble_sort.rb
> +    print array
Please remove the print statement and return your array at the end of the method.

2020-08-14 21:50 UTC, ikraamg commented on bubble_sort.rb
> +    print array
Please remove the print statement and return your array at the end of the method

2020-08-15 12:31 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far @team, you have just some minor changes to work :toolbox: :wrench: :hammer: on to get your project approved :checkered_flag:

- [ ] please remove all debugging code and leave only the functions.

### Please make all the required changes before use submit another code review.
## Happy Coding :tophat:

2020-08-15 12:31 UTC, elmejdki commented on bubble_sort.rb
> +p bub_sort_by(%w[hey hi hello]) { |left, right| left.length - right.length }
please remove all the debugging code and leave only your functions

2020-08-15 12:31 UTC, elmejdki commented on bubble_sort.rb
>  ##############################
remove this also

2020-08-15 12:39 UTC, mahmoud717 commented
didn't know that this was debugging code ( ;

2020-08-15 12:47 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Hi, it's me again,

I think you didn't understand me, you should delete the print methods, we should have only the functions inside the file, I have approved your project but please make that happen.

## Happy Coding :tophat:

2020-08-15 13:01 UTC, merged